title: Riddle Records
description: A site for diary, music, and art
author: 4mg

collections:
  diary:
    output: true
    permalink: /diary/:name/
  
  songs:
    output: true
    permalink: /disco/:name/

include:
  - jpg
  - png
  - favicon

exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle
  - vendor/cache
  - vendor

url: "https://enomi-4mg.github.io"
baseurl: "/Riddle-Records"

# Cloudinary settings
cloudinary_cloud_name: "dzq8y9qes"
cloudinary_url: "https://res.cloudinary.com/dzq8y9qes/image/upload"